from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        ############################################ UI - MAIN WINDOW ############################################
        # VENTANA PRINCIPAL
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 730)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 730))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 730))
        MainWindow.setStyleSheet("font-size: 14px; font-weight: bold; font-family: Century Gothic")
        # WIDGET CONTENEDOR
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # FRAME CONTENEDOR PRINCIPAL
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(5, 0, 1355, 690))
        self.frame.setStyleSheet("background: #FEFEFE; font-size: 14px; font-weight: bold; font-family: Century Gothic")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 210, 471, 71))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.label.setFont(font)
        self.label.setObjectName("label")
        # CONTENEDOR SIMPLEX
        self.widgetSimplex = QtWidgets.QWidget(self.frame)
        self.widgetSimplex.setEnabled(True)
        self.widgetSimplex.setGeometry(QtCore.QRect(0, 0, 1355, 690))
        self.widgetSimplex.setStyleSheet("")
        self.widgetSimplex.setObjectName("widgetSimplex")
        self.widgetSimplex.setVisible(False)
        # CONTENEDOR PERL
        self.widgetPerl = QtWidgets.QWidget(self.frame)
        self.widgetPerl.setEnabled(True)
        self.widgetPerl.setGeometry(QtCore.QRect(0, 0, 1355, 690))
        self.widgetPerl.setStyleSheet("")
        self.widgetPerl.setObjectName("widgetPerl")
        self.widgetPerl.setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        # MENÚ
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuM_todo = QtWidgets.QMenu(self.menubar)
        self.menuM_todo.setObjectName("menuM_todo")
        MainWindow.setMenuBar(self.menubar)
        # STATUSBAR
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # ACTION SIMPLEX
        self.actionSimplex = QtWidgets.QAction(MainWindow)
        self.actionSimplex.setObjectName("actionSimplex")
        # ACTION PERL
        self.actionPerl_CPM = QtWidgets.QAction(MainWindow)
        self.actionPerl_CPM.setObjectName("actionPerl_CPM")
        self.menuM_todo.addAction(self.actionSimplex)
        self.menuM_todo.addSeparator()
        self.menuM_todo.addAction(self.actionPerl_CPM)
        self.menubar.addAction(self.menuM_todo.menuAction())
        ########################################### UI - MÉTODO SIMPLEX ###########################################
        # GROUP BOX DATOS
        self.groupBoxDatos = QtWidgets.QGroupBox(self.widgetSimplex)
        self.groupBoxDatos.setGeometry(QtCore.QRect(30, 0, 450, 142))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxDatos.setFont(font)
        self.groupBoxDatos.setObjectName("groupBoxDatos")
        # LABEL VARIABLE
        self.lblVar = QtWidgets.QLabel(self.groupBoxDatos)
        self.lblVar.setGeometry(QtCore.QRect(40, 30, 300, 20))
        self.lblVar.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblVar.setFont(font)
        self.lblVar.setAutoFillBackground(False)
        self.lblVar.setStyleSheet("")
        self.lblVar.setObjectName("lblVar")
        self.lblVar.setStyleSheet("font-size: 16px")
        # INPUT VARIABLE
        self.inputVar = QtWidgets.QSpinBox(self.groupBoxDatos)
        self.inputVar.setGeometry(QtCore.QRect(350, 30, 40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.inputVar.setFont(font)
        self.inputVar.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.inputVar.setToolTipDuration(-27)
        self.inputVar.setKeyboardTracking(True)
        self.inputVar.setMinimum(2)
        self.inputVar.setObjectName("inputVar")
        # LABEL RESTRICCIONES
        self.lblRes = QtWidgets.QLabel(self.groupBoxDatos)
        self.lblRes.setGeometry(QtCore.QRect(40, 60, 300, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblRes.setFont(font)
        self.lblRes.setStyleSheet("")
        self.lblRes.setObjectName("lblRes")
        self.lblRes.setStyleSheet("font-size: 16px")
        # INPUT RESTRICCIONES
        self.inputRes = QtWidgets.QSpinBox(self.groupBoxDatos)
        self.inputRes.setGeometry(QtCore.QRect(350, 60, 40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.inputRes.setFont(font)
        self.inputRes.setMinimum(1)
        self.inputRes.setObjectName("inputRes")
        # BTN GENERAR
        self.btnGenerar = QtWidgets.QPushButton(self.groupBoxDatos)
        self.btnGenerar.setGeometry(QtCore.QRect(175, 100, 80, 30))
        self.btnGenerar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGenerar.setObjectName("btnGenerar")
        # GROUP BOX FUNCIÓN OBJETIVA
        self.groupBoxFuncObj = QtWidgets.QGroupBox(self.widgetSimplex)
        self.groupBoxFuncObj.setGeometry(QtCore.QRect(30, 155, 450, 135))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxFuncObj.setFont(font)
        self.groupBoxFuncObj.setObjectName("groupBoxFuncObj")
        # LABEL MAX Z
        self.lblTextMaxZ = QtWidgets.QLabel(self.groupBoxFuncObj)
        self.lblTextMaxZ.setGeometry(QtCore.QRect(20, 30, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblTextMaxZ.setFont(font)
        self.lblTextMaxZ.setObjectName("lblTextMaxZ")
        # TABLA FUNCIÓN OBJETIVA
        self.tableFuncObj = QtWidgets.QTableWidget(self.groupBoxFuncObj)
        self.tableFuncObj.setGeometry(QtCore.QRect(30, 60, 400, 68))
        self.tableFuncObj.setObjectName("tableFuncObj")
        self.tableFuncObj.setColumnCount(0)
        self.tableFuncObj.setRowCount(0)
        self.tableFuncObj.verticalHeader().setVisible(False)
        self.tableFuncObj.horizontalHeader().setDefaultAlignment(QtCore.Qt.AlignHCenter and QtCore.Qt.AlignVCenter and QtCore.Qt.AlignCenter)
        self.tableFuncObj.horizontalHeader().setDefaultSectionSize(50)
        self.tableFuncObj.horizontalHeader().setStyleSheet("color: #fff")
        self.tableFuncObj.setStyleSheet("border: none; font-size: 16px")
        # GROUP BOX RESTRICCIONES
        self.groupBoxRestriccion = QtWidgets.QGroupBox(self.widgetSimplex)
        self.groupBoxRestriccion.setGeometry(QtCore.QRect(30, 300, 450, 260))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxRestriccion.setFont(font)
        self.groupBoxRestriccion.setObjectName("groupBoxRestriccion")
        # TABLA RESTRICCIONES
        self.tableRestr = QtWidgets.QTableWidget(self.groupBoxRestriccion)
        self.tableRestr.setGeometry(QtCore.QRect(10, 30, 430, 220))
        self.tableRestr.setObjectName("tableRestr")
        self.tableRestr.setColumnCount(0)
        self.tableRestr.setRowCount(0)
        self.tableRestr.verticalHeader().setVisible(False)
        self.tableRestr.horizontalHeader().setDefaultAlignment(QtCore.Qt.AlignHCenter and QtCore.Qt.AlignVCenter and QtCore.Qt.AlignCenter)
        self.tableRestr.horizontalHeader().setDefaultSectionSize(50)
        self.tableRestr.horizontalHeader().setStyleSheet("color: #fff")
        self.tableRestr.setStyleSheet("border: none; font-size: 16px")
        # GROUP BOX ACCIONES
        self.groupBoxAcciones = QtWidgets.QGroupBox(self.widgetSimplex)
        self.groupBoxAcciones.setGeometry(QtCore.QRect(30, 570, 440, 111))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxAcciones.setFont(font)
        self.groupBoxAcciones.setObjectName("groupBoxAcciones")
        # BTN CALCULAR
        self.btnCalcular = QtWidgets.QPushButton(self.groupBoxAcciones)
        self.btnCalcular.setGeometry(QtCore.QRect(20, 30, 80, 30))
        self.btnCalcular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCalcular.setObjectName("btnCalcular")
        self.btnCalcular.setEnabled(False)
        # BTN NUEVO 
        self.btnNuevo = QtWidgets.QPushButton(self.groupBoxAcciones)
        self.btnNuevo.setGeometry(QtCore.QRect(130, 30, 80, 30))
        self.btnNuevo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNuevo.setObjectName("btnNuevo")
        # BTN SALIR
        self.btnSalir = QtWidgets.QPushButton(self.groupBoxAcciones)
        self.btnSalir.setGeometry(QtCore.QRect(240, 30, 80, 30))
        self.btnSalir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSalir.setObjectName("btnSalir")
        # BTN IMPRIMIR
        self.btnImprimir = QtWidgets.QPushButton(self.groupBoxAcciones)
        self.btnImprimir.setGeometry(QtCore.QRect(348, 30, 80, 30))
        self.btnImprimir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnImprimir.setObjectName("btnImprimir")
        self.btnImprimir.setEnabled(False)
        # BTN CALCULAR PIBOTE
        self.btnCalPibote = QtWidgets.QPushButton(self.groupBoxAcciones)
        self.btnCalPibote.setGeometry(QtCore.QRect(20, 70, 130, 30))
        self.btnCalPibote.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCalPibote.setObjectName("btnCalPibote")
        self.btnCalPibote.setEnabled(False)
        # BTN ANTERIROR TABLA
        self.btnPreviousTabla = QtWidgets.QPushButton(self.groupBoxAcciones)
        self.btnPreviousTabla.setGeometry(QtCore.QRect(170, 70, 120, 30))
        self.btnPreviousTabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPreviousTabla.setObjectName("btnPreviousTabla")
        self.btnPreviousTabla.setEnabled(False)
        # BTN SIGUIENTE TABLA
        self.btnNextTabla = QtWidgets.QPushButton(self.groupBoxAcciones)
        self.btnNextTabla.setGeometry(QtCore.QRect(310, 70, 120, 30))
        self.btnNextTabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNextTabla.setObjectName("btnNextTabla")
        self.btnNextTabla.setEnabled(False)
        # GROUP BOX RESULTADO
        self.groupBoxResul = QtWidgets.QGroupBox(self.widgetSimplex)
        self.groupBoxResul.setGeometry(QtCore.QRect(550, 0, 790, 680))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxResul.setFont(font)
        self.groupBoxResul.setObjectName("groupBoxResul")
        # LABEL FUNCION OBJETIVO
        self.lblMaxZ = QtWidgets.QTextBrowser(self.groupBoxResul)
        self.lblMaxZ.setGeometry(QtCore.QRect(20, 25, 750, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        self.lblMaxZ.setFont(font)
        self.lblMaxZ.setObjectName("lblMaxZ")
        self.lblMaxZ.setStyleSheet("border: none; font-size: 16px")
        # LABEL RESTRICCIONES
        self.lblRestricc = QtWidgets.QTextBrowser(self.groupBoxResul)
        self.lblRestricc.setGeometry(QtCore.QRect(20, 67, 750, 150))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        self.lblRestricc.setFont(font)
        self.lblRestricc.setObjectName("lblRestricc")
        self.lblRestricc.setStyleSheet("border: none")
        # TABLA RESULTADO
        self.tableResult = QtWidgets.QTableWidget(self.groupBoxResul)
        self.tableResult.setGeometry(QtCore.QRect(20, 220, 750, 255))
        self.tableResult.setObjectName("tableResult")
        self.tableResult.setColumnCount(0)
        self.tableResult.setRowCount(0)
        self.tableResult.verticalHeader().setVisible(False)
        self.tableResult.horizontalHeader().setVisible(False)
        self.tableResult.horizontalHeader().setDefaultAlignment(QtCore.Qt.AlignHCenter and QtCore.Qt.AlignVCenter and QtCore.Qt.AlignCenter)
        self.tableResult.horizontalHeader().setDefaultSectionSize(75)
        self.tableResult.setStyleSheet("border: none")
        # LABEL PIBOTE
        self.lblPibote = QtWidgets.QTextBrowser(self.groupBoxResul)
        self.lblPibote.setGeometry(QtCore.QRect(20, 478, 750, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        self.lblPibote.setFont(font)
        self.lblPibote.setObjectName("lblPibote")
        self.lblPibote.setStyleSheet("border: none; font-size: 18px")
        # GROUP BOX RESPUESTA
        self.groupBoxRespuesta = QtWidgets.QGroupBox(self.groupBoxResul)
        self.groupBoxRespuesta.setGeometry(QtCore.QRect(20, 540, 750, 130))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxRespuesta.setFont(font)
        self.groupBoxRespuesta.setObjectName("groupBoxRespuesta")
        self.groupBoxRespuesta.setHidden(True)
        # LABEL RESPUESTA
        self.lblRespuesta = QtWidgets.QTextBrowser(self.groupBoxRespuesta)
        self.lblRespuesta.setGeometry(QtCore.QRect(20, 40, 700, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        self.lblRespuesta.setFont(font)
        self.lblRespuesta.setObjectName("lblRespuesta")
        self.lblRespuesta.setStyleSheet("border: none; font-size: 18px")
        # LABEL TOTAL TABLAS
        self.lblTotalTable = QtWidgets.QTextBrowser(self.groupBoxRespuesta)
        self.lblTotalTable.setGeometry(QtCore.QRect(20, 80, 700, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        self.lblTotalTable.setFont(font)
        self.lblTotalTable.setObjectName("lblTotalTable")
        self.lblTotalTable.setStyleSheet("border: none; font-size: 18px")
        ########################################### UI - MÉTODO PERL ###########################################
        # GROUP BOX DATOS ACTIVIDADES
        self.groupBoxDatosPerl = QtWidgets.QGroupBox(self.widgetPerl)
        self.groupBoxDatosPerl.setGeometry(QtCore.QRect(30, 0, 1300, 80))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxDatosPerl.setFont(font)
        self.groupBoxDatosPerl.setObjectName("groupBoxDatosPerl")
        # LABEL ACTIVIDAD
        self.lblAct = QtWidgets.QLabel(self.groupBoxDatosPerl)
        self.lblAct.setGeometry(QtCore.QRect(40, 40, 300, 20))
        self.lblAct.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblAct.setFont(font)
        self.lblAct.setAutoFillBackground(False)
        self.lblAct.setStyleSheet("")
        self.lblAct.setObjectName("lblAct")
        self.lblAct.setStyleSheet("font-size: 16px")
        # INPUT ACTIVIDAD
        self.inputAct = QtWidgets.QSpinBox(self.groupBoxDatosPerl)
        self.inputAct.setGeometry(QtCore.QRect(350, 40, 40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.inputAct.setFont(font)
        self.inputAct.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.inputAct.setToolTipDuration(-27)
        self.inputAct.setKeyboardTracking(True)
        self.inputAct.setMinimum(2)
        self.inputAct.setObjectName("inputAct")
        # BTN GENERAR
        self.btnGenerarPerl = QtWidgets.QPushButton(self.groupBoxDatosPerl)
        self.btnGenerarPerl.setGeometry(QtCore.QRect(420, 35, 80, 30))
        self.btnGenerarPerl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGenerarPerl.setObjectName("btnGenerarPerl")
        # BTN CALCULAR PERL
        self.btnCalcularPerl = QtWidgets.QPushButton(self.groupBoxDatosPerl)
        self.btnCalcularPerl.setGeometry(QtCore.QRect(1000, 35, 80, 30))
        self.btnCalcularPerl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCalcularPerl.setObjectName("btnCalcularPerl")
        # GROUP BOX RESULTADO ACTIVIDADES
        self.groupBoxrResPerl = QtWidgets.QGroupBox(self.widgetPerl)
        self.groupBoxrResPerl.setGeometry(QtCore.QRect(30, 100, 1300, 580))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxrResPerl.setFont(font)
        self.groupBoxrResPerl.setObjectName("groupBoxrResPerl")
        # TABLA ACTIVIDADES
        self.tableActividades = QtWidgets.QTableWidget(self.groupBoxrResPerl)
        self.tableActividades.setGeometry(QtCore.QRect(5, 5, 1290, 575))
        self.tableActividades.setObjectName("tableActividades")
        self.tableActividades.setColumnCount(0)
        self.tableActividades.setRowCount(0)
        self.tableActividades.verticalHeader().setVisible(False)
        self.tableActividades.horizontalHeader().setDefaultAlignment(QtCore.Qt.AlignHCenter and QtCore.Qt.AlignVCenter and QtCore.Qt.AlignCenter)
        self.tableActividades.horizontalHeader().setDefaultSectionSize(75)
        self.tableActividades.horizontalHeader().setStyleSheet("color: #fff")
        self.tableActividades.setStyleSheet("border: 1px solid #000; font-size: 16px")
        
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        #################################### MAIN WINDOW ####################################
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.label.setText(_translate("MainWindow", "BIENVENIDO"))
        self.menuM_todo.setTitle(_translate("MainWindow", "Método"))
        self.actionSimplex.setText(_translate("MainWindow", "Simplex"))
        self.actionPerl_CPM.setText(_translate("MainWindow", "Perl"))
        #################################### UI - SIMPLEX ####################################
        self.groupBoxDatos.setTitle(_translate("MainWindow", "Datos"))
        self.lblVar.setText(_translate("MainWindow", "Ingrese el número de variables:"))
        self.lblRes.setText(_translate("MainWindow", "Ingrese el número de restricciones:"))
        self.btnGenerar.setText(_translate("MainWindow", "GENERAR"))
        self.groupBoxRestriccion.setTitle(_translate("MainWindow", "Restricciones"))
        self.lblTextMaxZ.setText(_translate("MainWindow", "MAX Z ="))
        self.groupBoxFuncObj.setTitle(_translate("MainWindow", "Función Objetivo"))
        self.groupBoxAcciones.setTitle(_translate("MainWindow", "Acciones"))
        self.btnCalcular.setText(_translate("MainWindow", "CALCULAR"))
        self.btnCalPibote.setText(_translate("MainWindow", "CALCULAR PIVOTE"))
        self.btnPreviousTabla.setText(_translate("MainWindow", "ANTERIOR TABLA"))
        self.btnNextTabla.setText(_translate("MainWindow", "SIGUIENTE TABLA"))
        self.btnNuevo.setText(_translate("MainWindow", "NUEVO"))
        self.btnSalir.setText(_translate("MainWindow", "SALIR"))
        self.btnSalir.setText(_translate("MainWindow", "SALIR"))
        self.btnImprimir.setText(_translate("MainWindow", "IMPRIMIR"))
        self.groupBoxResul.setTitle(_translate("MainWindow", "Resultado"))
        self.groupBoxRespuesta.setTitle(_translate("MainWindow", "Respuesta"))
        #################################### UI - PERL ####################################
        self.groupBoxDatosPerl.setTitle(_translate("MainWindow", "Datos"))
        self.lblAct.setText(_translate("MainWindow", "Ingrese el número de actividades:"))
        self.btnGenerarPerl.setText(_translate("MainWindow", "GENERAR"))
        self.btnCalcularPerl.setText(_translate("MainWindow", "CALCULAR"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle(QtWidgets.QStyleFactory.create('Fusion'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())